import os
from contextlib import AbstractContextManager
from typing import Any

# Functions
def version() -> str: ...
def clamp(x: Any, a: Any, b: Any) -> Any: ...
def vec2(x: int, y: int) -> Vec2: ...
def rect(x: int, y: int, w: int, h: int) -> Rect: ...
def color(r: int, g: int, b: int, a: int = 255) -> Color: ...

class DuplicateIDError(RuntimeError): ...

# Core classes
class Vec2:
    x: int
    y: int
    def __init__(self, x: int = 0, y: int = 0) -> None: ...

class Rect:
    x: int
    y: int
    w: int
    h: int
    def __init__(self, x: int = 0, y: int = 0, w: int = 0, h: int = 0) -> None: ...

class Color:
    r: int
    g: int
    b: int
    a: int
    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255) -> None: ...

class Style:
    size: Vec2
    padding: int
    spacing: int
    indent: int
    title_height: int
    scrollbar_size: int
    thumb_size: int
    def get_color(self, index: int) -> Color: ...
    def set_color(self, index: int, color: Color) -> None: ...

class Context:
    style: Style
    def __init__(self) -> None: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def begin(self) -> None: ...
    def end(self) -> None: ...
    def abort_frame(self) -> None: ...
    @property
    def in_frame(self) -> bool: ...
    def set_focus(self, id: int) -> None: ...
    def get_id(self, data: Any) -> int: ...
    def push_id(self, data: Any) -> None: ...
    def pop_id(self) -> None: ...
    def push_clip_rect(self, rect: Rect) -> None: ...
    def pop_clip_rect(self) -> None: ...
    def get_clip_rect(self) -> Rect: ...
    def check_clip(self, rect: Rect) -> int: ...
    def input_mousemove(self, x: int, y: int) -> None: ...
    def input_mousedown(self, x: int, y: int, btn: int) -> None: ...
    def input_mouseup(self, x: int, y: int, btn: int) -> None: ...
    def input_scroll(self, x: int, y: int) -> None: ...
    def input_keydown(self, key: int) -> None: ...
    def input_keyup(self, key: int) -> None: ...
    def input_text(self, text: str) -> None: ...
    def layout_row(
        self, widths: list[int] | tuple[int, ...] | None, height: int
    ) -> None: ...
    def layout_width(self, width: int) -> None: ...
    def layout_height(self, height: int) -> None: ...
    def layout_begin_column(self) -> None: ...
    def layout_end_column(self) -> None: ...
    def layout_set_next(self, rect: Rect, relative: int) -> None: ...
    def layout_next(self) -> Rect: ...
    def text(self, text: str) -> None: ...
    def label(self, text: str) -> None: ...
    def button(
        self, label: str, icon: int = 0, opt: int = 0, key: Any = None
    ) -> int: ...
    def checkbox(
        self, label: str, state: bool | int, key: Any = None
    ) -> tuple[int, int]: ...
    def textbox(
        self, buf: str, bufsz: int = 256, opt: int = 0, key: Any = None
    ) -> tuple[int, str]: ...
    def textbox_ex(
        self, buf: str, bufsz: int = 256, opt: int = 0, key: Any = None
    ) -> tuple[int, str]: ...
    def slider(
        self,
        value: float,
        low: float,
        high: float,
        step: float = 0,
        fmt: str = "%.2f",
        opt: int = 0,
        key: Any = None,
    ) -> tuple[int, float]: ...
    def number(
        self,
        value: float,
        step: float,
        fmt: str = "%.2f",
        opt: int = 0,
        key: Any = None,
    ) -> tuple[int, float]: ...
    def header(self, label: str, opt: int = 0) -> int: ...
    def begin_treenode(self, label: str, opt: int = 0) -> int: ...
    def end_treenode(self) -> None: ...
    def begin_window(self, title: str, rect: Rect, opt: int = 0) -> int: ...
    def end_window(self) -> None: ...
    def window(
        self, title: str, x: int, y: int, w: int, h: int, opt: int = 0
    ) -> Window: ...
    def open_popup(self, name: str) -> None: ...
    def begin_popup(self, name: str) -> int: ...
    def end_popup(self) -> None: ...
    def begin_panel(self, name: str, opt: int = 0) -> None: ...
    def end_panel(self) -> None: ...
    def draw_rect(self, rect: Rect, color: Color) -> None: ...
    def draw_box(self, rect: Rect, color: Color) -> None: ...
    def draw_text(self, text: str, pos: Vec2, color: Color) -> None: ...
    def draw_icon(self, id: int, rect: Rect, color: Color) -> None: ...
    def reset_command_iterator(self) -> None: ...
    def get_current_container(self) -> ContainerWrapper | None: ...
    def get_container(self, name: str) -> ContainerWrapper | None: ...
    def mouse_over(self, rect: Rect) -> int: ...
    def bring_to_front(self, container: ContainerWrapper) -> None: ...
    def treenode(self, label: str, opt: int = 0) -> AbstractContextManager[bool]: ...
    def popup(self, name: str) -> AbstractContextManager[bool]: ...
    def panel(
        self, name: str, opt: int = 0
    ) -> AbstractContextManager[ContainerWrapper | None]: ...
    def column(self) -> AbstractContextManager[None]: ...
    def id_scope(self, data: Any) -> AbstractContextManager[None]: ...
    def update_control(self, id: int, rect: Rect, opt: int = 0) -> None: ...
    def draw_control_frame(
        self, id: int, rect: Rect, colorid: int, opt: int = 0
    ) -> None: ...
    def draw_control_text(
        self, text: str, rect: Rect, colorid: int, opt: int = 0
    ) -> None: ...
    @property
    def hover(self) -> int: ...
    @property
    def focus(self) -> int: ...
    @property
    def last_id(self) -> int: ...
    @property
    def mouse_pos(self) -> Vec2: ...
    @property
    def mouse_delta(self) -> Vec2: ...
    @property
    def mouse_down(self) -> int: ...
    @property
    def mouse_pressed(self) -> int: ...
    @property
    def key_down(self) -> int: ...
    @property
    def key_pressed(self) -> int: ...
    def next_command(
        self,
    ) -> (
        BaseCommand
        | RectCommand
        | TextCommand
        | IconCommand
        | ClipCommand
        | JumpCommand
        | None
    ): ...
    @staticmethod
    def vec2(x: int, y: int) -> Vec2: ...
    @staticmethod
    def rect(x: int, y: int, w: int, h: int) -> Rect: ...
    @staticmethod
    def color(r: int, g: int, b: int, a: int = 255) -> Color: ...

class Window:
    is_open: bool
    title: str
    rect: Rect
    opt: int
    def __init__(self, ctx: Context, title: str, rect: Rect, opt: int = 0) -> None: ...
    def __enter__(self) -> Window: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class ContainerWrapper:
    rect: Rect
    body: Rect
    content_size: Vec2
    scroll: Vec2
    open: int
    @property
    def zindex(self) -> int: ...

class BaseCommand:
    type: int
    size: int

class RectCommand:
    type: int
    rect: Rect
    color: Color

class TextCommand:
    type: int
    font: Any
    pos: Vec2
    color: Color
    text: str

class IconCommand:
    type: int
    rect: Rect
    icon_id: int
    color: Color

class ClipCommand:
    type: int
    rect: Rect

class JumpCommand:
    type: int

class Textbox:
    text: str
    def __init__(self, buffer_size: int = 128) -> None: ...
    def update(self, ctx: Context, opt: int = 0) -> tuple[int, str]: ...

# Constants
class Clip:
    PART: int
    ALL: int

class Command:
    JUMP: int
    CLIP: int
    RECT: int
    TEXT: int
    ICON: int
    MAX: int

class ColorIndex:
    TEXT: int
    BORDER: int
    WINDOWBG: int
    TITLEBG: int
    TITLETEXT: int
    PANELBG: int
    BUTTON: int
    BUTTONHOVER: int
    BUTTONFOCUS: int
    BASE: int
    BASEHOVER: int
    BASEFOCUS: int
    SCROLLBASE: int
    SCROLLTHUMB: int
    MAX: int

class Icon:
    CLOSE: int
    CHECK: int
    COLLAPSED: int
    EXPANDED: int
    MAX: int

class Result:
    ACTIVE: int
    SUBMIT: int
    CHANGE: int

class Option:
    ALIGNCENTER: int
    ALIGNRIGHT: int
    NOINTERACT: int
    NOFRAME: int
    NORESIZE: int
    NOSCROLL: int
    NOCLOSE: int
    NOTITLE: int
    HOLDFOCUS: int
    AUTOSIZE: int
    POPUP: int
    CLOSED: int
    EXPANDED: int

class Mouse:
    LEFT: int
    RIGHT: int
    MIDDLE: int

class Key:
    SHIFT: int
    CTRL: int
    ALT: int
    BACKSPACE: int
    RETURN: int

class EventType:
    QUIT: int
    MOUSEMOTION: int
    MOUSEDOWN: int
    MOUSEUP: int
    MOUSEWHEEL: int
    KEYDOWN: int
    KEYUP: int
    TEXT: int
    RESIZE: int

class Event:
    @property
    def type(self) -> int: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def button(self) -> int: ...
    @property
    def key(self) -> int: ...
    @property
    def keycode(self) -> int: ...
    @property
    def text(self) -> str: ...
    def __init__(
        self,
        type: int,
        x: int = 0,
        y: int = 0,
        button: int = 0,
        key: int = 0,
        keycode: int = 0,
        text: str = "",
    ) -> None: ...

def poll_event() -> Event | None: ...

# Renderer functions
def render(ctx: Context, bg: Color | None = None) -> None: ...
def renderer_init() -> None: ...
def renderer_init_window(
    title: str = "pymui", width: int = 800, height: int = 600, resizable: bool = True
) -> None: ...
def renderer_resize(width: int, height: int) -> None: ...
def renderer_shutdown() -> None: ...
def load_font(source: str | os.PathLike[str] | bytes, size: float = 16.0) -> None: ...
def reset_font() -> None: ...
def font_loaded() -> bool: ...
def renderer_draw_rect(rect: Rect, color: Color) -> None: ...
def renderer_draw_text(text: str, pos: Vec2, color: Color) -> None: ...
def renderer_draw_icon(icon_id: int, rect: Rect, color: Color) -> None: ...
def renderer_get_text_width(text: str, length: int = -1) -> int: ...
def renderer_get_text_height() -> int: ...
def renderer_set_clip_rect(rect: Rect) -> None: ...
def renderer_clear(color: Color) -> None: ...
def renderer_present() -> None: ...
